spring.application.name=SmartHire
# ????

# ?????
server.port=8080
server.servlet.context-path:

# ??????
logging:
level:
root: DEBUG
com.resume_ai_project.smarthire: DEBUG
org.springframework.security: INFO

# ??????
spring.profiles.active=dev

# application.properties
spring.datasource.url=jdbc:mysql://localhost:3306/smarthire?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zhsh1230


# JWT ?? (???????? 32 ??????????????)
app.jwtSecret=MySuperSecretKeyForJWTTokenGenerationMustBeLongEnoughToAvoidErrors1234567890

# JWT ???? (??) - ??? 24 ??
app.jwtExpirationMs=86400000

mybatis-plus.type-enums-package=com.resume_ai_project.smarthire.entity
# ÃÂÃÂ§ÃÂÃÂ¦ÃÂÃÂÃÂÃÂ§ÃÂÃÂÃÂÃÂ¨ XML Mapper ÃÂÃÂ¥ÃÂÃÂÃÂÃÂ ÃÂÃÂ¨ÃÂÃÂ½ÃÂÃÂ½ÃÂÃÂ¯ÃÂÃÂ¼ÃÂÃÂÃÂÃÂ©ÃÂÃÂÃÂÃÂ¿ÃÂÃÂ¥ÃÂÃÂÃÂÃÂ DevTools ÃÂÃÂ©ÃÂÃÂÃÂÃÂÃÂÃÂ¥ÃÂÃÂÃÂÃÂ¯ÃÂÃÂ¦ÃÂÃÂÃÂÃÂ¶ÃÂÃÂ§ÃÂÃÂ±ÃÂÃÂ»ÃÂÃÂ¥ÃÂÃÂÃÂÃÂ ÃÂÃÂ¨ÃÂÃÂ½ÃÂÃÂ½ÃÂÃÂ¥ÃÂÃÂÃÂÃÂ¨ÃÂÃÂ©ÃÂÃÂÃÂÃÂ®ÃÂÃÂ©ÃÂÃÂ¢ÃÂÃÂ
mybatis-plus.mapper-locations=
# ÃÂÃÂ§ÃÂÃÂ¦ÃÂÃÂÃÂÃÂ§ÃÂÃÂÃÂÃÂ¨ Spring Data JPA ÃÂÃÂ¨ÃÂÃÂÃÂÃÂªÃÂÃÂ¥ÃÂÃÂÃÂÃÂ¨ÃÂÃÂ©ÃÂÃÂÃÂÃÂÃÂÃÂ§ÃÂÃÂ½ÃÂÃÂ®
spring.data.jpa.repositories.enabled=false
# ÃÂÃÂ§ÃÂÃÂ¦ÃÂÃÂÃÂÃÂ§ÃÂÃÂÃÂÃÂ¨ JPA ÃÂÃÂ¨ÃÂÃÂÃÂÃÂªÃÂÃÂ¥ÃÂÃÂÃÂÃÂ¨ÃÂÃÂ©ÃÂÃÂÃÂÃÂÃÂÃÂ§ÃÂÃÂ½ÃÂÃÂ®
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration