spring.application.name=SmartHire
# ????

# ?????
server.port=8080
server.servlet.context-path:

# ??????
logging:
level:
root: DEBUG
com.resume_ai_project.smarthire: DEBUG
org.springframework.security: INFO

# ??????
spring.profiles.active=dev

# application.properties
spring.datasource.url=jdbc:mysql://localhost:3306/smarthire?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zhsh1230


# JWT ?? (???????? 32 ??????????????)
app.jwtSecret=MySuperSecretKeyForJWTTokenGenerationMustBeLongEnoughToAvoidErrors1234567890

# JWT ???? (??) - ??? 24 ??
app.jwtExpirationMs=86400000

mybatis-plus.type-enums-package=com.resume_ai_project.smarthire.entity
mybatis-plus.mapper-locations=
spring.data.jpa.repositories.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration