# ???
spring.datasource.url=jdbc:mysql://localhost:3307/smart_resume?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root

# Redis??????
#spring.redis.host=localhost
#spring.redis.port=6379

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# MinIO
minio.endpoint=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=resumes

# Elasticsearch??????
spring.elasticsearch.uris=http://localhost:9200
# MyBatis-Plus ??
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# MyBatis-Plus ??
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.resume_ai_project.smarthire.entity
# ???? Spring Data JPA ???????
spring.data.jpa.repositories.enabled=false
# ???? JPA ???????????
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
# ??????mock ? llm
app.parser.type=mock